[package]
name = "dominoes"
version = "0.0.1"
authors = ["Jake Marsden <jakemarsdenjm@gmail.com>"]
license = "MIT"
publish = false
edition = "2018"

[lib]
name = "dominoes"
path = "src/lib.rs"

[profile.release]
codegen-units = 1
lto = true
panic = 'abort'
